language: node_js

node_js:
  - 12

install:
  - npm install
  
script:
  - npm test
addons:
  browserstack:
    username: "Your BrowserStack username"
    access_key:
      secure: "The secure string output of `travis encrypt`"
addons:
  browserstack:
    username: "browserstack1548"
    access_key:
      secure: "CQXyJkr6b2SU4IW1eEKBhfcWMklNk+IOq/2o9aOqYmuJ4EdicJSOMWh5z5YIzO6vuGHc65BtrgQc50V5b0sjitiECQzK1jna2ZzNiEok2BzYeskZ2MHk8NirzVueTHdo/HS5FSzbdxld+OyKhW8LX/LjB0DlvtP6tq9uiit5RJljSfv9Tdu9ftr5Avb46fqtT+flK4hjhfmLSCnnjkEtKcjl9TZVS85Rpt5PEL/D9F3/eP3KiI+AolLjbAPYKYKqcLMvPmFDSQwxsQHJoY6wEzl8dH3f/xFkPCbjE27Vlg6C6+bp78hf/qO3D3KSm9zWyVVOGikJ06AMf8dC72uqBHnkVo3j0qkOtYTENOxvms72O79h3uHpjahc3GcDLeENAh12PSJFgNNmgkpCsrIedNxVu7h99ouIYckgPtA6B8xu1YN5PmHfTNHtpl9lnTcmy/YvtETgRSeaOmtoFOy7tFuS+R4pXm6DH0pAXo7tQXY/Pnw/tMT9oT0z5IZSl/h1aMuovzenuDt0zxm5ZbitFnrPEUccxySyzhAjY4LgIpqQHmUtKzmP+X9kdj/IM5ZCpquR9CSyWb9hAFW2K4Gzy2ezNkerjimdHv6SfLdBblQKMTHi5fJw1UL+tKb2PZh7KiTDUbrO2LkC6VZRpjxQoMTOTArgCHify22Gvj6oo4A="