language: node_js

node_js:
  - 12

install:
  - npm install
  
script:
  - npm test

addons:
  browserstack:
    username: "browserstack1548"
    access_key:
      secure: "mu3op5S3/dkiK0dYkIO3alR/NfkGlkO4FRlat0zcWFmpL76261c6QuhX8sacaYgqpIv2EgJ0ShlXb+oyoFiy48yiZZYbAaP0tWzlqR4gm+NttuebeVxudcCE9ltn1xmTfVPm5akUHaYkutEv0F8AvLcc0BjwltUb1jKo6Dq8yBpJeNt91vgOPReYP8Q950mH3s2nHAUGPz9V8rG7gsqWltPCAIRuexMqWEjo1uqKlMWR1es5xUykJ1i4g0emKXOPOeqdvWpmYDNyn9esndb/M9aIgTtsLOK460txFDUFCNIeI/ItuIOuIrB7GUoTLCNYpbEa3vWa+48RO2jSi2IxEIuvOto5PWdL+4TPF2oT7Vftxa8My/6X2+CtQ30ZvLRCZlIwtl4hSqcBor1I0U1b0Lx2VJCokYDavrbA/PPmv5Tv48DWw/UkLGIQpD/bmfwDt1ux7Y2X88sIctaNKP+zlhBo+QrJFnv7oOoGc5sFjxH4oSiZlIwk7RjyBZXoMFDt7clY4Rofz5d3/Op7tvexm3pura1RIwVxhii24+2Utr0aMxX2NITCgWmnRSlgmULrrAwsSe2uiOktp6+0JCmqKx+w9g1rHZARAwDlF6au+OusYpz2BU15J/6R7kAYoMhjfjQdfljAH5TMncAi7ZMk3alUb08BQXDFAO3SqjUIELY="